name: four_restaurants
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.3
  intl: ^0.17.0
  dotenv: ^4.2.0
  material_symbols_icons: ^4.2801.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
